[application]
name = "hemi"
out_dir = "target/dx/hemi/release/web/public"
asset_dir = "assets"
default_platform = "web"

[web.app]
title = "HemiTyper"

[web.watcher]
reload_html = true
watch_path = ["src", "assets", "./"]

[web.resource]
script = []

[web.resource.dev]
style = []
script = []

[[web.proxy]]
backend = "http://localhost:8000/api/"

[application.tools]
tailwindcss = { config = "assets/tailwind.config.js" }
