name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install wasm-bindgen-cli
        run: cargo install -f wasm-bindgen-cli --version 0.2.92

      - name: Install Dioxus CLI
        run: cargo install dioxus-cli

      - name: Update project dependencies
        run: |
          cargo update -p wasm-bindgen --precise 0.2.92
          cargo clean

      - name: Build project
        run: dx build --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
